### PR TITLE
add paper, rock, scissors tdd

### PR DESCRIPTION
**Pull request by manuelbarzi**

### CODE REVIEW

**Comment by ebertran** [comment]
oki doki

**Comment by Sol-22** [comment]
ok

**Comment by gemmacn** [comment]
ok

**Comment by mangione77** [comment]
All ok!

**Comment by codeshakti** [comment]
ok!

**Comment by pausarobe** [comment]
gj ok!

**Comment by Kevinrosmusic** [comment]
:)

**Pull request merged**
