### PR TITLE
add array reduce example to js doc

### PR DESCRIPTION
**Pull request by manuelbarzi**
i want to  add array reduce doc into js readme
please @agandia9, @mtzfactory, @marcrg, @Micheloncio, @mangione77...

### CODE REVIEW

**Comment by Micheloncio** [comment]
OK

**Comment by marcrg** [comment]
It's Ok! Go!!!!

**Comment by agandia9** [comment]
Ok! 😃

**Comment by mangione77** [comment]
Ok!!

**Comment by Kevinrosmusic** [comment]
:)

**Comment by gemmacn** [comment]
ok

**Comment by mtzfactory** [comment]
genial!

**Comment by codeshakti** [comment]
dale!

**Comment by pausarobe** [comment]
ok

**Comment by Sol-22** [comment]
Whats? Jeje

**Pull request merged**
