### PR TITLE
update doc0

### PR DESCRIPTION
**Pull request by manuelbarzi**

### CODE REVIEW

**Comment by mangione77** [comment]
Ok!

**Comment by pausarobe** [comment]
ok

**Comment by ebertran** [comment]
ok

**Comment by gemmacn** [comment]
ok

**Comment by marcrg** [comment]
Perfect!

**Comment by codeshakti** [comment]
dale

**Comment by Micheloncio** [comment]
bad!!

**Comment by Sol-22** [comment]
ok

**Pull request merged**
